### ISSUE TITLE
Can view player email addresses

### ISSUE THREAD

**Issue by cheshire137** [LexLadiesCode/lexplaypacman#9]
We should adjust the players/show.json.jbuilder page to not include the email field. See http://www.lexplaypacman.com/players/4.json

![screen shot 2014-04-04 at 12 58 41 pm](https://cloud.githubusercontent.com/assets/82317/2618038/67f4ef02-bc1a-11e3-94a8-082f1743f4b0.png)

Note I don't think we link to this page anywhere. Could probably remove the player show page entirely.

**Comment by eliriveire** [comment]
Took out the :email field
